spring:
  datasource:
    url: jdbc:h2:mem:avalondb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true # make 404 exception handled by GlobalExceptionHandler
  web:
    resources:
      add-mappings: false # disable ResourceHttpRequestHandler

logging.level:
  org.hibernate.SQL: debug
