server:
  servlet:
    context-path: /v1

spring:
  datasource:
    url: jdbc:h2:mem:avalondb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true # make 404 exception handled by GlobalExceptionHandler
  web:
    resources:
      add-mappings: false # disable ResourceHttpRequestHandler

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: simple

logging.level:
  org.hibernate.SQL: debug

jwt:
  access-validity: 1800000
  refresh-validity: 1209600000
  key: happilyeverafterhappilyeverafterhappilyeverafterhahappilyeverhappilyeverafterhappilyeverafterhappilyeverafterhahappilyever
