server:
  servlet:
    context-path: /v1

spring:
  datasource:
    url: jdbc:h2:mem:avalondb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  mvc:
    throw-exception-if-no-handler-found: true # make 404 exception handled by GlobalExceptionHandler
  web:
    resources:
      add-mappings: false # disable ResourceHttpRequestHandler

management:
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: health,info, openapi, swaggerui
  endpoint:
    health:
      show-details: always
  info:
    git:
      mode: simple
  server:
    port: 9090

logging.level:
  org.hibernate.SQL: debug

jwt:
  key: happilyeverafterhappilyeverafterhappilyeverafterhahappilyeverhappilyeverafterhappilyeverafterhappilyeverafterhahappilyever

# springdoc
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
    default-models-expand-depth: -1
  packages-to-scan: com.avalon.avalonchat.domain
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  use-management-port: true

