name: Deploy on Cloud Run

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build by Gradle & Deploy on CloudRun
    environment: dev
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_APP_NAME }}
    steps:
      - name: Checkout to github with submodule
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.REPO_ACCESS }}
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'gradle'

      - uses: oNaiPs/secrets-to-env-action@v1
        with:
          secrets: ${{ toJSON(secrets) }}

      - name: Execute build
        uses: gradle/gradle-build-action@v2.2.1
        with:
          arguments: build --exclude-task test

      - name: Setup Gcloud Account
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_email: ${{ secrets.GCP_EMAIL }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build the stack
        run: docker-compose up -d

      - name: Execute Jib - Docker build & Push
        uses: gradle/gradle-build-action@v2.2.1
        with:
          arguments: jib

      - name: Deploy Docker image
        run: gcloud run deploy ${{ secrets.GCP_PROJECT_ID }} --image $IMAGE_NAME --region asia-northeast3 --platform managed
